### ISSUE TITLE
Undefined property: Mix\Http\Application::$session

### ISSUE THREAD

**Issue by dickens7** [mix-php/mix-http-session#1]
# http-session 组件使用中遇到 Undefined property: Mix\Http\Application::$session
> * 单次请求正常，异常 在使用ab 压测时发生
> * 服务使用协程模式

```
[notice] 2019-06-03 18:50:46 <7995> [message] Undefined property: Mix\Http\Application::$session
[code] 8 [type] Mix\Exception\ErrorException
[file] /home/seven/php/longyuan-experience-api/applications/http/src/Controllers/Api/UserController.php [line] 19
[trace] #0 /home/seven/php/longyuan-experience-api/applications/http/src/Controllers/Api/UserController.php(19): Mix\Core\Error::appError(8, 'Undefined prope...', '/home/seven/php...', 19, Array)
#1 [internal function]: Http\Controllers\Api\UserController->actionLogin(Object(Mix\Http\Message\Request\HttpRequest), Object(Mix\Http\Message\Response\HttpResponse))
#2 /home/seven/php/longyuan-experience-api/vendor/mix/framework/src/Core/Middleware/MiddlewareHandler.php(51): call_user_func_array(Array, Array)
#3 /home/seven/php/longyuan-experience-api/vendor/mix/framework/src/Core/Middleware/MiddlewareHandler.php(54): Mix\Core\Middleware\MiddlewareHandler->run(Array, Object(Mix\Http\Message\Request\HttpRequest), Object(Mix\Http\Message\Response\HttpResponse))
#4 /home/seven/php/longyuan-experience-api/applications/http/src/Middleware/AfterMiddleware.php(24): Mix\Core\Middleware\MiddlewareHandler->Mix\Core\Middleware\{closure}()
#5 /home/seven/php/longyuan-experience-api/vendor/mix/framework/src/Core/Middleware/MiddlewareHandler.php(55): Http\Middleware\AfterMiddleware->handle(Array, Object(Closure))
#6 /home/seven/php/longyuan-experience-api/vendor/mix/framework/src/Core/Middleware/MiddlewareHandler.php(54): Mix\Core\Middleware\MiddlewareHandler->run(Array, Object(Mix\Http\Message\Request\HttpRequest), Object(Mix\Http\Message\Response\HttpResponse))
#7 /home/seven/php/longyuan-experience-api/applications/http/src/Middleware/BeforeMiddleware.php(40): Mix\Core\Middleware\MiddlewareHandler->Mix\Core\Middleware\{closure}()
#8 /home/seven/php/longyuan-experience-api/vendor/mix/framework/src/Core/Middleware/MiddlewareHandler.php(55): Http\Middleware\BeforeMiddleware->handle(Array, Object(Closure))
#9 /home/seven/php/longyuan-experience-api/vendor/mix/http/src/Application.php(54): Mix\Core\Middleware\MiddlewareHandler->run(Array, Object(Mix\Http\Message\Request\HttpRequest), Object(Mix\Http\Message\Response\HttpResponse))
#10 /home/seven/php/longyuan-experience-api/vendor/mix/http/src/Application.php(38): Mix\Http\Application->runAction('POST', '/api/user/login')
#11 /home/seven/php/longyuan-experience-api/vendor/mix/http-server/src/HttpServer.php(160): Mix\Http\Application->run()
#12 [internal function]: Mix\Http\Server\HttpServer->onRequest(Object(Swoole\Http\Request), Object(Swoole\Http\Response))
#13 /home/seven/php/longyuan-experience-api/vendor/mix/http-server/src/HttpServer.php(151): call_user_func(Array, Object(Swoole\Http\Request), Object(Swoole\Http\Response))
#14 [internal function]: Mix\Http\Server\HttpServer->Mix\Http\Server\{closure}()
#15 /home/seven/php/longyuan-experience-api/vendor/mix/framework/src/Core/Coroutine.php(112): call_user_func_array(Object(Closure), Array)
#16 {main}

```

### session配置
```
        // Session
        'session' => [
            // 依赖引用
            'ref' => beanname(Mix\Http\Session\HttpSession::class),
        ],
        // Session
        [
            // 类路径
            'class' => Mix\Http\Session\HttpSession::class,
            // 属性
            'properties' => [
                // 处理器
                'handler' => [
                    // 依赖引用
                    'ref' => beanname(Mix\Http\Session\RedisHandler::class),
                ],
                // session键名
                'name' => 'session_id',
                // 生存时间
                'maxLifetime' => 7200,
                // 过期时间
                'cookieExpires' => 0,
                // 有效的服务器路径
                'cookiePath' => '/',
                // 有效域名/子域名
                'cookieDomain' => '',
                // 仅通过安全的 HTTPS 连接传给客户端
                'cookieSecure' => false,
                // 仅可通过 HTTP 协议访问
                'cookieHttpOnly' => false,
            ],
        ],

        // Session处理器
        [
            // 类路径
            'class' => Mix\Http\Session\RedisHandler::class,
            // 属性
            'properties' => [
                // 连接池
                'pool' => [
                    // 组件引用
                    'component' => 'redisPool',
                ],
                // Key前缀
                'keyPrefix' => 'SESSION:',
            ],
        ],
```
### 控制器代码
```
 
    public function actionIndex()
    {
       
        if (!app()->session->has('user')) {
            sleep(1);
            app()->session->set('user', ['user'=>'test']);
        }
        $data = [
            'session_id' => app()->session->getSessionId()
        ];
        return $this->success($data);
    }
```

### ab 压测命令
```
ab -n 5 -c 5 -p postdata.txt -T application/x-www-form-urlencoded "http://127.0.0.1:3000/api/index"
```
> postdata.txt 中的值为   username=user&password=123456&

**Comment by onanying** [comment]
@dickens7  这是一个php bug，但是 swoole 官方无法解决 https://github.com/swoole/swoole-src/issues/2625   ，你需要在使用这个组件时，使用 __get 方法获取组件

```
        /** @var HttpSession $session */
        $session = app()->__get("session");
        if (!$session->has('user')) {
            sleep(1);
            $session->set('user', ['user' => 'test']);
        }
        $data = [
            'session_id' => $session->getSessionId(),
        ];
```

后续版本框架会取消使用属性的方式获取组件。
